Too good to be true.  I don't know what the svn merge command does with -x -b, but id doesn't merge without whitespace changes.  Reverting the previous change to bin/mergedevbranch.  - Legacy-Id: 10549

diff --git a/bin/mergedevbranch b/bin/mergedevbranch
--- a/bin/mergedevbranch
+++ b/bin/mergedevbranch
@@ -149,7 +149,7 @@ read -p "Continue with diff? [Y/n] "
 [ "$REPLY" = "Y" -o  "$REPLY" = "y" -o  "$REPLY" = "" ] || exit
 
 note "Diff:"
-svn diff -c $rev -x"-u -b" $repo/$branch | less
+svn diff -c $rev $repo/$branch | less
 
 echo ""
 read -p "Additional descriptive text (hit return for none): "
@@ -165,10 +165,10 @@ read -p "Continue with the merge? [Y/n] "
 
 note "Do the merge:"
 if [[ $rev =~ : ]]; then
-    svn merge -r $rev -x"-u -b" ${repo}/$branch . || die "Merge of $branch @$rev failed.  The merge command was:
+    svn merge -r $rev ${repo}/$branch . || die "Merge of $branch @$rev failed.  The merge command was:
   svn merge -r $rev ${repo}/$branch ."
 else
-    svn merge -c $rev -x"-u -b" ${repo}/$branch . || die "Merge of $branch @$rev failed.  The merge command was:
+    svn merge -c $rev ${repo}/$branch . || die "Merge of $branch @$rev failed.  The merge command was:
   svn merge -c $rev ${repo}/$branch ."
 fi
 
