More Py2/3 adaptations fetched from production.  - Legacy-Id: 17333

diff --git a/bin/mm_hourly b/bin/mm_hourly
--- a/bin/mm_hourly
+++ b/bin/mm_hourly
@@ -6,10 +6,20 @@
 # $DTDIR/etc/cron.d/datatracker which should be symlinked from
 # /etc/cron.d/
 
+export LANG=en_US.UTF-8
+export PYTHONIOENCODING=utf-8
+
+# Make sure we stop if something goes wrong:
+program=${0##*/}
+trap 'echo "$program($LINENO): Command failed with error code $? ([$$] $0 $*)"; exit 1' ERR
+
 DTDIR=/a/www/ietf-datatracker/web
 cd $DTDIR/
 
 # Set up the virtual environment
 source $DTDIR/env/bin/activate
 
-$DTDIR/ietf/manage.py import_mailman_listinfo
+logger -p user.info -t cron "Running $DTDIR/bin/mm_hourly"
+
+## XXX commented out pending rewrite -- mailman 2 python interface is not available under Python 3
+# $DTDIR/ietf/manage.py import_mailman_listinfo
