Rip out more unused stuff, and update copyright based on TLP  - Legacy-Id: 19418

diff --git a/docker/rsync-extras b/docker/rsync-extras
--- a/docker/rsync-extras
+++ b/docker/rsync-extras
@@ -1,127 +1,104 @@
 #!/bin/bash
 
-version=0.10
+version=0.11
 program=${0##*/}
 progdir=${0%/*}
 if [ "$progdir" = "$program" ]; then progdir="."; fi
 if [ "$progdir" = "." ]; then progdir="$PWD"; fi
-parent=$(dirname $progdir)
+parent=$(dirname "$progdir")
 if [ "$parent" = "." ]; then parent="$PWD"; fi
 
-export LANG=C
 
-# ----------------------------------------------------------------------
 function usage() {
     cat <<EOF
 NAME
 	$program - Copy additional data files from the ietf server
 
 SYNOPSIS
-	$program [OPTIONS]
+	$program [OPTIONS] [DESTINATION]
 
 DESCRIPTION
-
 	This script copies additional data files used by the datatracker
-        from the ietf server to a local directory, for instance drafts,
-        charters, rfcs, agendas, minutes, etc.
+	from the ietf server to a local directory, for instance drafts,
+	charters, rfcs, agendas, minutes, etc.
 
+	If no destination is given, the default is data/developers.
+
+OPTIONS
 EOF
-    echo -e "OPTIONS"
-    if   [ "$(uname)" = "Linux" ]; then
-        egrep "^[	]+[-][A-Za-z| -]+\*?\)[	]+[A-Za-z].+#" $0 | tr -s "\t|" "\t," | sed -r -e 's/\)[ \t]+([A-Z]+)=\$2[^#]*#/=\1\t/' -e 's/\)[^#]*#/\t/'
-    else
-        egrep "^[	]+[-][A-Za-z| -]+\*?\)[	]+[A-Za-z].+#" $0 | sed 's/\|.*\$2[^#]*#/	/'| sed -E 's/\|.*\)[^#]*#/	/'
-    fi
+    sed -n -E "s|(^\s+-[A-Za-z])\).*#(.*)|\1 \2|p" "$0"
     cat <<EOF
 
-FILES
-
 AUTHOR
-	Written by Henrik Levkowetz, <henrik@levkowetz.com>
+	Written by:
+    	Henrik Levkowetz, <henrik@levkowetz.com>
+		Lars Eggert, <lars@eggert.org>
 
 COPYRIGHT
-
 	Copyright (c) 2016 IETF Trust and the persons identified as authors of
-	the code. All rights reserved.  License 'Simplified BSD', as specified
-	in http://opensource.org/licenses/BSD-3-Clause.
-	
-EOF
+	the code. All rights reserved. Redistribution and use in source and
+	binary forms, with or without modification, is permitted pursuant to,
+	and subject to the license terms contained in, the Revised BSD
+	License set forth in Section 4.c of the IETF Trust’s Legal Provisions
+	Relating to IETF Documents(https://trustee.ietf.org/license-info).
 
+EOF
 }
 
-# ----------------------------------------------------------------------
+
 function die() {
     echo -e "\n$program: error: $*" >&2
     exit 1
 }
 
-function note() { 
-	if [ -n "$VERBOSE" ]; then echo -e "$*"; fi
-}
 
-# ----------------------------------------------------------------------
 function version() {
 	echo -e "$program $version"
 }
 
-# ----------------------------------------------------------------------
 trap 'echo "$program($LINENO): Command failed with error code $? ([$$] $0 $*)"; exit 1' ERR
 
 
-# ----------------------------------------------------------------------
 # Option parsing
-
-# Options
 shortopts=hvV
-longopts=help,verbose,version
-
-# Default values
-
-if   [ "$(uname)" = "Linux" ]; then
-    args=$(getopt -o "$shortopts" --long "$longopts" -n '$program' -- $SV "$@")
-    if [ $? != 0 ] ; then die "Terminating..." >&2 ; exit 1 ; fi
-    eval set -- "$args"
-    sed="sed -r"
-else
-    # Darwin, BSDs
-    args=$(getopt -o$shortopts $SV $*)
-    if [ $? != 0 ] ; then die "Terminating..." >&2 ; exit 1 ; fi
-    set -- $args
-    sed="sed -E"
-fi
+args=$(getopt -o$shortopts $SV $*)
+if [ $? != 0 ] ; then die "Terminating..." >&2 ; exit 1 ; fi
+set -- $args
 
 while true ; do
     case "$1" in
-	-h| --help)	usage; exit;;		# Show this help, then exit
-	-v| --verbose)	VERBOSE=1;;		# Be more talkative
-	-V| --version)	version; exit;;		# Show program version, then exit
-	--)		shift; break;;
-	*) die "Internal error, inconsistent option specification: '$1'";;
+    	-h)    usage; exit;;   # Show this help, then exit
+    	-v)    VERBOSE=1;;	   # Be more talkative
+    	-V)    version; exit;; # Show program version, then exit
+    	--)    shift; break;;
+    	*) die "Internal error, inconsistent option specification: '$1'";;
     esac
     shift
 done
 
-# ----------------------------------------------------------------------
 # The program itself
+if [ $# -lt 1 ]; then
+    DEST_ROOT=data/developers
+else
+    DEST_ROOT="${1%/}"
+fi
+echo "Using destination $DEST_ROOT"
 
-[ $# -lt 1 ] && die "Missing argument: rsync destination"
-
-DEST_ROOT="${1%/}"
 for dir in charter conflict-reviews internet-drafts review rfc slides status-changes yang; do
   dest="$DEST_ROOT/ietf-ftp/$dir"
+  mkdir -p "$dest"
   echo "Fetching $dest ..."
   rsync -auz ${VERBOSE:+--info=progress2} rsync.ietf.org::everything-ftp/$dir/ $dest/
 done
 
 for dir in floor photo; do
   dest="$DEST_ROOT/media/$dir"
+  mkdir -p "$dest"
   echo "Fetching $dest ..."
   rsync -auz ${VERBOSE:+--info=progress2} rsync.ietf.org::dev.media/$dir/ $dest/
 done
 
-
-  dest="$DEST_ROOT/archive/id"
-  echo "Fetching $dest ..."
-  rsync -auz ${VERBOSE:+--info=progress2} rsync.ietf.org::id-archive/ $dest/
-
-
+dest="$DEST_ROOT/archive/id"
+mkdir -p "$dest"
+echo "Fetching $dest ..."
+rsync -auz ${VERBOSE:+--info=progress2} rsync.ietf.org::id-archive/ $dest/
diff --git a/docker/run b/docker/run
--- a/docker/run
+++ b/docker/run
@@ -7,9 +7,8 @@ if [ "$progdir" = "$program" ]; then progdir="."; fi
 if [ "$progdir" = "." ]; then progdir="$PWD"; fi
 parent=$(dirname "$progdir")
 if [ "$parent" = "." ]; then parent="$PWD"; fi
-if [[ $(uname) =~ CYGWIN.* ]]; then parent=$(echo "$parent" | sed -e 's/^\/cygdrive\/\(.\)/\1:/'); fi
 
-# ----------------------------------------------------------------------
+
 function usage() {
     cat <<EOF
 NAME
@@ -19,60 +18,46 @@ SYNOPSIS
 	$program [OPTIONS] ARGS
 
 DESCRIPTION
+	This is a wrapper which runs an	Ubuntu-based docker image which
+	has been set up with the dependencies needed to easily run the
+	IETF datatracker in development mode.
 
-	This is a wrapper which runs docker with suitable arguments on a
-	debian-based docker image which has been set up with the dependencies
-	needed to easily run the IETF datatracker in development mode.  By
-	default, it expects to find the MySQL database files at
-	$parent/data/mysql, which is mapped inside the
-	container to /var/lib/mysql, and it will set up a home directory for
-	the current user ($USER) and map it to $HOME.
+	MySQL database files at data/mysql will be used; if they do not exist,
+	a database dump will be retrieved and restored on first run.
 
+OPTIONS
 EOF
-    echo -e "OPTIONS"
-    if   [ "$(uname)" = "Linux" ] || [ "$(uname)" = "Darwin" ]; then
-        grep -E "^[	]+[-][A-Za-z| -]+\*?\)[	]+[A-Za-z].+#" "$0" | tr -s "\t|" "\t," | sed -r -e 's/\)[ \t]+([A-Z]+)=\$2[^#]*#/=\1\t/' -e 's/\)[^#]*#/\t/'
-    else
-        grep -E "^[	]+[-][A-Za-z| -]+\*?\)[	]+[A-Za-z].+#" "$0" | sed 's/\|.*\$2[^#]*#/	/'| sed -E 's/\|.*\)[^#]*#/	/'
-    fi
+    sed -n -E "s|(^\s+-[A-Za-z])\).*#(.*)|\1 \2|p" "$0"
     cat <<EOF
 
-FILES
-
 AUTHOR
-	Written by Henrik Levkowetz, <henrik@levkowetz.com>
+	Written by:
+		Henrik Levkowetz, <henrik@levkowetz.com>
+		Lars Eggert, <lars@eggert.org>
 
 COPYRIGHT
-
-	Copyright (c) 2015 IETF Trust and the persons identified as authors of
-	the code. All rights reserved.  License 'Simplified BSD', as specified
-	in http://opensource.org/licenses/BSD-3-Clause.
-
+	Copyright (c) 2016 IETF Trust and the persons identified as authors of
+	the code. All rights reserved. Redistribution and use in source and
+	binary forms, with or without modification, is permitted pursuant to,
+	and subject to the license terms contained in, the Revised BSD
+	License set forth in Section 4.c of the IETF Trust’s Legal Provisions
+	Relating to IETF Documents(https://trustee.ietf.org/license-info).
 EOF
-
 }
 
-# ----------------------------------------------------------------------
+
 function die() {
     echo -e "\n$program: error: $*" >&2
     exit 1
 }
 
-# ----------------------------------------------------------------------
+
 function version() {
 	echo -e "$program $version"
 }
 
-# ----------------------------------------------------------------------
+
 trap 'echo "$program($LINENO): Command failed with error code $? ([$$] $0 $*)"; exit 1' ERR
-
-
-# ----------------------------------------------------------------------
-# Option parsing
-
-# Options
-shortopts=hp:vVcC
-longopts=help,port=,version,cached,no-cached
 
 # Default values
 MYSQLDIR=$parent/data/mysql
@@ -80,26 +65,22 @@ PORT=8000
 REPO="ietf/datatracker-environment"
 CACHED=':cached'
 
-if   [ "$(uname)" = "Linux" ]; then
-    args=$(getopt -o "$shortopts" --long "$longopts" -n '$program' -- $SV "$@")
-    if [ $? != 0 ] ; then die "Terminating..." >&2 ; exit 1 ; fi
-    eval set -- "$args"
-else
-    # Darwin, BSDs
-    args=$(getopt -o$shortopts $SV $*)
-    if [ $? != 0 ] ; then die "Terminating..." >&2 ; exit 1 ; fi
-    set -- $args
-fi
+# Option parsing
+shortopts=hp:VcC
+
+args=$(getopt -o$shortopts $SV $*)
+if [ $? != 0 ] ; then die "Terminating..." >&2 ; exit 1 ; fi
+set -- $args
 
 while true ; do
     case "$1" in
-	-c| --cached)	CACHED=':cached';;	# Use cached disk access to reduce system load
-	-C| --no-cached)	CACHED=':consistent';;	# Use fully synchronized disk access
-	-h| --help)	usage; exit;;		# Show this help, then exit
-	-p| --port)	PORT=$2; shift;;	# Bind the container's port 8000 to external port PORT
-	-V| --version)	version; exit;;		# Show program version, then exit
-	--)		shift; break;;
-	*) die "Internal error, inconsistent option specification: '$1'";;
+    	-c)    CACHED=':cached';;	  # Use cached disk access to reduce system load
+    	-C)    CACHED=':consistent';; # Use fully synchronized disk access
+    	-h)    usage; exit;;		  # Show this help, then exit
+    	-p)    PORT=$2; shift;;	      # Bind the container's port 8000 to external port PORT
+    	-V)    version; exit;;		  # Show program version, then exit
+    	--)    shift; break;;
+    	*) die "Internal error, inconsistent option specification: '$1'";;
     esac
     shift
 done
@@ -107,8 +88,6 @@ done
 if [ -z "$TAG" ]; then
   TAG=$(basename "$(svn info "$parent" | grep ^URL | awk '{print $2}')")
 fi
-
-# ----------------------------------------------------------------------
 
 echo "Starting a docker container for '$REPO:$TAG'."
 mkdir -p "$MYSQLDIR"
diff --git a/docker/updatedb b/docker/updatedb
--- a/docker/updatedb
+++ b/docker/updatedb
@@ -1,5 +1,4 @@
 #!/bin/bash
-# -*- indent-with-tabs: 1 -*-
 
 version=0.20
 program=${0##*/}
@@ -9,7 +8,7 @@ if [ "$progdir" = "." ]; then progdir="$PWD"; fi
 parent=$(dirname "$progdir")
 if [ "$parent" = "." ]; then parent="$PWD"; fi
 
-# ----------------------------------------------------------------------
+
 function usage() {
     cat <<EOF
 NAME
@@ -19,89 +18,68 @@ SYNOPSIS
 	$program [OPTIONS] ARGS
 
 DESCRIPTION
-
 	This script downloads a dump of the IETF database and loads into the
 	local sql server if it is newer than the current dump.
 
+OPTIONS
 EOF
-    echo -e "OPTIONS"
-    if   [ "$(uname)" = "Linux" ]; then
-        grep -E "^[	]+[-][A-Za-z| -]+\*?\)[	]+[A-Za-z].+#" "$0" | tr -s "\t|" "\t," | sed -r -e 's/\)[ \t]+([A-Z]+)=\$2[^#]*#/=\1\t/' -e 's/\)[^#]*#/\t/'
-    else
-        grep -E "^[	]+[-][A-Za-z| -]+\*?\)[	]+[A-Za-z].+#" "$0" | sed 's/\|.*\$2[^#]*#/	/'| sed -E 's/\|.*\)[^#]*#/	/'
-    fi
+    sed -n -E "s|(^\s+-[A-Za-z])\).*#(.*)|\1 \2|p" "$0"
     cat <<EOF
 
-FILES
-
 AUTHOR
-	Written by Henrik Levkowetz, <henrik@levkowetz.com>
+	Written by:
+		Henrik Levkowetz, <henrik@levkowetz.com>
+		Lars Eggert, <lars@eggert.org>
 
 COPYRIGHT
-
-	Copyright (c) 2015 IETF Trust and the persons identified as authors of
-	the code. All rights reserved.  License 'Simplified BSD', as specified
-	in http://opensource.org/licenses/BSD-3-Clause.
-
+	Copyright (c) 2016 IETF Trust and the persons identified as authors of
+	the code. All rights reserved. Redistribution and use in source and
+	binary forms, with or without modification, is permitted pursuant to,
+	and subject to the license terms contained in, the Revised BSD
+	License set forth in Section 4.c of the IETF Trust’s Legal Provisions
+	Relating to IETF Documents(https://trustee.ietf.org/license-info).
 EOF
-
 }
 
-# ----------------------------------------------------------------------
+
 function die() {
     echo -e "\n$program: error: $*" >&2
     exit 1
 }
 
-# ----------------------------------------------------------------------
+
 function version() {
 	echo -e "$program $version"
 }
 
-# ----------------------------------------------------------------------
+
 trap 'echo "$program($LINENO): Command failed with error code $? ([$$] $0 $*)"; exit 1' ERR
 
-
-# ----------------------------------------------------------------------
 # Option parsing
-
-# Options
 shortopts=DLZhqvV
-longopts=no-download,no-load,no-zap,help,version
-
 LOAD=1
 DOWNLOAD=1
 DROP=1
 
-if   [ "$(uname)" = "Linux" ]; then
-    args=$(getopt -o "$shortopts" --long "$longopts" -n "$program" -- $SV "$@")
-    if [ $? != 0 ] ; then die "Terminating..." >&2 ; exit 1 ; fi
-    eval set -- "$args"
-else
-    # Darwin, BSDs
-    args=$(getopt -o$shortopts $SV $*)
-    if [ $? != 0 ] ; then die "Terminating..." >&2 ; exit 1 ; fi
-    set -- $args
-fi
+args=$(getopt -o$shortopts $SV $*)
+if [ $? != 0 ] ; then die "Terminating..." >&2 ; exit 1 ; fi
+set -- $args
 
 while true ; do
     case "$1" in
-	-D| --no-download)	DOWNLOAD="";;	#Don't download, use existing file
-	-L| --no-load)	LOAD=""; ;;		#	Don't load the database
-	-Z| --no-zap)	DROP="";;		#	Don't drop new tables
-	-h| --help)	usage; exit;;		#	Show this help, then exit
-	-V| --version)	version; exit;;		#	Show program version, then exit
-	--)		shift; break;;
-	*) die "Internal error, inconsistent option specification: '$1'";;
+    	-D)    DOWNLOAD="";;	# Don't download, use existing file
+    	-L)    LOAD=""; ;;		# Don't load the database
+    	-Z)    DROP="";;		# Don't drop new tables
+    	-h)    usage; exit;;	# Show this help, then exit
+    	-V)    version; exit;;	# Show program version, then exit
+    	--)    shift; break;;
+    	*) die "Internal error, inconsistent option specification: '$1'";;
     esac
     shift
 done
 
-# ----------------------------------------------------------------------
 # The program itself
-
 DATADIR=$parent/data
-
 DUMP=ietf_utf8.sql.gz
 if [ "$DOWNLOAD" ]; then
     echo "Fetching database dump..."
